{{- if not .Values.confluent.credentials.existingSecret }}
{{- if or .Values.confluent.credentials.apiKey .Values.confluent.credentials.apiSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "confluent-identity-operator.credentialsSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "confluent-identity-operator.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.confluent.credentials.apiKeyKey }}: {{ .Values.confluent.credentials.apiKey | quote }}
  {{ .Values.confluent.credentials.apiSecretKey }}: {{ .Values.confluent.credentials.apiSecret | quote }}
{{- end }}
{{- end }}
