apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "confluent-identity-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "confluent-identity-operator.labels" . | nindent 4 }}
  {{- if or (and .Values.workloadIdentity.enabled .Values.workloadIdentity.clientId) .Values.serviceAccount.annotations }}
  annotations:
    {{- if and .Values.workloadIdentity.enabled .Values.workloadIdentity.clientId }}
    azure.workload.identity/client-id: {{ .Values.workloadIdentity.clientId | quote }}
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
